apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-config
  namespace: trip
data:
  # Real services on your Windows host, reachable from pods via host.minikube.internal
  PAYMENT_URL: "http://host.minikube.internal:8082"
  DRIVER_URL: "http://host.minikube.internal:8000/api/v1"
  RIDER_URL:  "http://host.minikube.internal:3001"

  # App config
  PYTHONUNBUFFERED: "1"
  # If you change these, also update the DATABASE_URL in trip-secrets
  DB_NAME: "tripdb"
  DB_USER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
